Features/timeline cards
opc-cpvp/OPC.PowerApps pull request #103
Opened 2020-08-07 18:50 UTC by GabrielFG

- Displaying date created rather than last modified in the event card
- Ordering of timeline now done by created first (and activities and notes are well sorted together)
- Displaying actual owner/created by when assigning using the On Behalf field
- Events are now bilingual
- Now removing state from a activity cards

2020-08-11 19:01 UTC, Sargatos commented on src/Compliance.Plugins.Tests/RemoveTimelineCardStatusPluginTests.cs
> +                pluginContext.InputParameters["FetchXml"].Should().Be("<attribute name=\"testAttribute\"/>  <attribute name=\"testAttribute2\"/>");
You could also use Should().NotContain(). This way if the fetchxml changes you don't need to also change the assert part.

2020-08-11 19:20 UTC, Sargatos commented on src/Compliance.Solution/Solution/Entities/Account/Entity.xml
> +      <AutoCreateAccessTeams>0</AutoCreateAccessTeams>
I don't know what that does, but in my PR I removed them just in case.

2020-08-11 19:28 UTC, Sargatos commented on src/Compliance.Solution/Solution/Entities/opc_reminder/Entity.xml
> +        <attribute PhysicalName="opc_notifyadditionalusers">
This field was removed because it is not used anymore.

2020-08-11 19:33 UTC, Sargatos commented on src/Compliance.Solution/Solution/Other/RibbonCustomization.xml
> +<RibbonDiffXml xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
What is this file for again? It seems like it is referenced in Solution.xml

2020-08-11 19:40 UTC, Sargatos commented
Is it normal that the owner of the timeline notes changes to the new owner of the file except for the latest created?

2020-08-11 19:45 UTC, GabrielFG commented on src/Compliance.Plugins.Tests/RemoveTimelineCardStatusPluginTests.cs
> +                pluginContext.InputParameters["FetchXml"].Should().Be("<attribute name=\"testAttribute\"/>  <attribute name=\"testAttribute2\"/>");
Will do.

2020-08-11 19:46 UTC, GabrielFG commented on src/Compliance.Solution/Solution/Entities/Account/Entity.xml
> +      <AutoCreateAccessTeams>0</AutoCreateAccessTeams>
Will do.

2020-08-11 19:47 UTC, GabrielFG commented on src/Compliance.Solution/Solution/Other/RibbonCustomization.xml
> +<RibbonDiffXml xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
Not sure.. I'll check if I can remove it.

2020-08-11 19:59 UTC, GabrielFG commented on src/Compliance.Plugins.Tests/MultiLanguagePluginTests.cs
> +            public void timeline_records_strings_should_turn_to_english_when_ui_is_english()
I think I should test 2 sets of strings. instead if possible and rename the test. One english and french, as the setup would be the same, only the parameters would differ.

2020-08-11 20:01 UTC, GabrielFG commented on src/Compliance.Solution/Solution/Entities/Account/Entity.xml
> +      <AutoCreateAccessTeams>0</AutoCreateAccessTeams>
On second thought, this might just be new stuff added by Dynamics for some new feature. Maybe we should just leave it as it will always come back. I'll do some small amount of research.

2020-08-11 20:01 UTC, GabrielFG commented on src/Compliance.Solution/Solution/Entities/opc_reminder/Entity.xml
> +        <attribute PhysicalName="opc_notifyadditionalusers">
Will remove.

2020-08-13 01:08 UTC, joshcampbell191 commented on src/Compliance.Plugins/RemoveTimelineCardStatusPlugin.cs
> +                if (localContext.PluginExecutionContext.MessageName == PluginMessage.RetrieveTimelineWallRecords
You should invert this statement to avoid nesting.

2020-08-13 01:09 UTC, joshcampbell191 commented on src/Compliance.Plugins/RemoveTimelineCardStatusPlugin.cs
> +                throw new InvalidPluginExecutionException($"An error occurred in the plug-in. MultiLanguage: {ex.Message}", ex);
The plugin name should be updated.

2020-08-14 15:05 UTC, pierluc-ssoucy commented on src/Compliance.Plugins/ChangeEventPlugin.cs
> +                    new FieldChangeTracker(nameof(opc_complaint.opc_intakeofficer), "Intake Officer", "Intake Officer") // TODO: No translation done yet
I believe the term in french is "Agent d'admission"

2020-08-14 15:15 UTC, pierluc-ssoucy commented on src/Compliance.Plugins.Tests/ChangeEventPluginTests.cs
> +            public static Entity TestUser
the changeeventplugin requires the entity to be registered to work properly.

2020-08-14 15:19 UTC, pierluc-ssoucy commented on src/Compliance.Plugins/RemoveTimelineCardStatusPlugin.cs
> +    public class RemoveTimelineCardStatusPlugin : PluginBase
I wonder if this should be its own plugin or if we should package it in the AnnotationAuthor (and rename it), given they're both for the exact context. Unless I am mistaking and the usage of AnnotherAuthor extends beyond the timeline? Thoughts? @joshcampbell191 @Sargatos @GabrielFG

2020-08-14 15:38 UTC, joshcampbell191 commented on src/Compliance.Plugins/RemoveTimelineCardStatusPlugin.cs
> +    public class RemoveTimelineCardStatusPlugin : PluginBase
Agreed with @pierluc-ssoucy. The AnnotationAuthorPlugin is currently used to override the default behavior of displaying the owner as the author for annotations. Both of these can be bundled together in order to centralize the changes to the Annotation entity.

2020-08-14 15:42 UTC, GabrielFG commented on src/Compliance.Plugins.Tests/ChangeEventPluginTests.cs
> +            public static Entity TestUser
I could leave out the fullname attribute and just leave the ID though, that would be enough for the tests.

2020-08-14 15:44 UTC, GabrielFG commented on src/Compliance.Plugins/RemoveTimelineCardStatusPlugin.cs
> +    public class RemoveTimelineCardStatusPlugin : PluginBase
Agreed too, I will bundle them together and rename the file.

2020-08-14 20:24 UTC, GabrielFG commented on src/Compliance.Solution/Solution/Entities/Account/Entity.xml
> +      <AutoCreateAccessTeams>0</AutoCreateAccessTeams>
May not be a new feature per say, but just like other options next to it (which are disabled with the value 0 like this one), it's just dynamics stuff. Since this has been added to both our environments, it will most likely just come back. So I don't think it's worth removing.

2020-08-14 20:43 UTC, GabrielFG commented on src/Compliance.Solution/Solution/Other/RibbonCustomization.xml
> +<RibbonDiffXml xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
Wondering if you had this in your first template PR and removed it? As this file only has a "Templates" section and the rest is empty, or would you think it's not related?

2020-08-17 14:11 UTC, GabrielFG commented on src/Compliance.Solution/Solution/Other/RibbonCustomization.xml
> +<RibbonDiffXml xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
@Sargatos Not sure if you saw my last message. Would you have an idea?

2020-08-17 14:12 UTC, GabrielFG commented on src/Compliance.Solution/Solution/Entities/Account/Entity.xml
> +      <AutoCreateAccessTeams>0</AutoCreateAccessTeams>
@Sargatos What do you think?

2020-08-17 19:17 UTC, GabrielFG commented on src/Compliance.Solution/Solution/Other/RibbonCustomization.xml
> +<RibbonDiffXml xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
I have removed it from the solution and it still seems to import properly.

2020-08-17 19:25 UTC, GabrielFG commented
> Is it normal that the owner of the timeline notes changes to the new owner of the file except for the latest created?

@Sargatos Just want to document what we had discussed on teams regarding this. It is normal as the new record gets created after all the cases get assigned to the new owner before the new event gets created. this is the case since the workflow is in Post operation, which is needed to get the pre and post images. If we really want this to be addressed, a possible solution would be to do like annotations and replace the owner on the RetrieveTimeline message.

2020-09-02 19:06 UTC, GabrielFG commented
@Sargatos Decided to go the simple route for test setup for the timeline record json as the other ways involved reading arrays of primitive values and not a full json blob. Let me know if you have other suggestions.

2020-09-03 15:29 UTC, pierluc-ssoucy requested changes

2020-09-03 15:29 UTC, pierluc-ssoucy commented on src/Compliance.Plugins.Tests/TimelineTransformationsTests.cs
> +                    Assert.Equal(createdOnBehalf["Id"], owner["Id"]);
We probably should be more consistent in our assertions by always using Should or [FluentAssertions](https://fluentassertions.com/introduction)

2020-09-03 15:30 UTC, pierluc-ssoucy commented on src/Compliance.Plugins.Tests/timelinerecords.json
> +﻿{
As discussed, we probably want to change this to a string constant to minimize IO in unit tests.

2020-09-03 21:27 UTC, GabrielFG commented on src/Compliance.Plugins.Tests/TimelineTransformationsTests.cs
> +                    Assert.Equal(createdOnBehalf["Id"], owner["Id"]);
To document our findings, dynamic objects don't support extension methods, so casting would be required which makes the Should not as straight forward.

2020-09-03 21:29 UTC, pierluc-ssoucy approved these changes

2020-09-03 21:34 UTC, merged