Update Solution - Compliance: PBI 559,588,589 - add alternate key, fi…
opc-cpvp/OPC.PowerApps pull request #109
Opened 2020-09-11 01:28 UTC by mitchkirady

Fixes:
- PBI 559: Alternate Key for Allegation Reference Number
- PBI 588: Remove Status Reason from Close stages in BPF
- PBI 589: Set Intake Officer when moving back to Intake stage in BPF
- PBI 589: Set Intake Officer when assigning complaint

Note that some french descriptions are flagged as being removed from the a9da30f commit, however those are all from out of the box option sets for activity entities, so I don't see any impact. I'm not sure how come they are being flagged as being removed since they weren't touched by these fixes.

For testing, you can publish build #1.0.422 to your own Development environment, since we don't have enough database capacity to create new environments in the PROD tenant (need at least 1 GB).

2020-09-14 20:15 UTC, Sargatos commented on src/Compliance.Solution/Solution/Workflows/Complaint-AssignStageExit-SetIntakeOfficer-0E1F06C2-102A-4264-AE27-E8367C257AC4.xaml.data.xml
> +    <LocalizedName languagecode="1033" description="Complaint - Assign/Stage Exit - Set Intake Officer" />
Shouldn't the Display Name of the process start with "Individual Complaint" like the rest?

2020-09-14 22:25 UTC, mitchkirady commented on src/Compliance.Solution/Solution/Workflows/Complaint-AssignStageExit-SetIntakeOfficer-0E1F06C2-102A-4264-AE27-E8367C257AC4.xaml.data.xml
> +    <LocalizedName languagecode="1033" description="Complaint - Assign/Stage Exit - Set Intake Officer" />
The reason I renamed it is because the workflow actually runs on the "Complaint" entity. Although it's called on Stage Exit from the Individual Complaint BPF, it also runs on "Assign" of a Complaint (which is not related to the BPF), so I think it makes more sense to rename it.

@pierluc-ssoucy - Thoughts?

2020-09-15 12:23 UTC, Sargatos commented on src/Compliance.Solution/Solution/Workflows/Complaint-AssignStageExit-SetIntakeOfficer-0E1F06C2-102A-4264-AE27-E8367C257AC4.xaml.data.xml
> +    <LocalizedName languagecode="1033" description="Complaint - Assign/Stage Exit - Set Intake Officer" />
ahhh, make sense. And is it normal that the lookup for this process in the bpf still has the old name?
![image](https://user-images.githubusercontent.com/21164740/93209849-ae1d5100-f72c-11ea-8f36-cf306402cf40.png)

2020-09-16 02:01 UTC, mitchkirady commented on src/Compliance.Solution/Solution/Workflows/Complaint-AssignStageExit-SetIntakeOfficer-0E1F06C2-102A-4264-AE27-E8367C257AC4.xaml.data.xml
> +    <LocalizedName languagecode="1033" description="Complaint - Assign/Stage Exit - Set Intake Officer" />
No that's a good catch, thanks @Sargatos! I've applied the fix.

2020-09-16 12:44 UTC, Sargatos requested changes

2020-09-16 12:44 UTC, Sargatos commented on src/Compliance.Solution/Solution/Other/Solution.xml
> -      <RootComponent type="381" id="{4710a2e7-53cc-ea11-a812-000d3af46489}" behavior="0" />
I'm pretty sure this is needed for the environment variable for the templates. 
It also makes me realize that I should probably find a better schema name.

2020-09-16 13:29 UTC, mitchkirady commented on src/Compliance.Solution/Solution/Other/Solution.xml
> -      <RootComponent type="381" id="{4710a2e7-53cc-ea11-a812-000d3af46489}" behavior="0" />
@Sargatos - Interesting, I'm not sure why this was removed after doing an unpack+commit. This branch isn't behind on any commits. Do you know when that was added to the solution?

2020-09-16 14:39 UTC, mitchkirady commented on src/Compliance.Solution/Solution/Other/Solution.xml
> -      <RootComponent type="381" id="{4710a2e7-53cc-ea11-a812-000d3af46489}" behavior="0" />
These lines have been manually added.

2020-09-16 15:48 UTC, Sargatos approved these changes
It all seems good.

2020-09-17 12:10 UTC, merged