Features/duplicatedetectionrules
opc-cpvp/OPC.PowerApps pull request #110
Opened 2020-09-21 19:52 UTC by GabrielFG

- Now exporting duplicate detection rules to bring across environments
- Rules need to be unpublished prior to exportation, this means:
    1. the powershell script in this PR will upublish/publish the rules for you
    2. The "Export and Commit Solution Data" pipeline will use the powershell script to unpublish, export and then re-publish the rules in the given environment when done.
- Deleting certain default rules when importing, this will only be needed when first creating a new environment and importing the package for the first time. The rules then won't come back and have no way to be accidently be exported into our data.

2020-09-22 20:49 UTC, pierluc-ssoucy requested changes

2020-09-22 20:49 UTC, pierluc-ssoucy commented on src/Compliance.Solution/Data/Lookups/data.xml
> +        <field name="ownerid" value="a5d21787-0ed1-ea11-a813-000d3a0c5524" lookupentity="systemuser" lookupentityname="Package Deployer" />
It seems like are overriding the owner of all the records, not sure if that is what we should be doing.

2020-09-22 20:49 UTC, pierluc-ssoucy commented on azure-pipelines/unpack-commit-solution-data.yml
> +  condition: always()
Why is this needed?

2020-09-22 20:49 UTC, pierluc-ssoucy commented on src/Compliance.Package/set_duplicaterule_publishstate.ps1
> +﻿Param(
Unless those scripts are used by the Compliance.Package project, I believe this should be at the same spot as the other pipeline scripts.

https://github.com/opc-cpvp/OPC.PowerApps/tree/master/azure-pipelines/scripts

2020-09-22 20:52 UTC, GabrielFG commented on azure-pipelines/unpack-commit-solution-data.yml
> +  condition: always()
@pierluc-ssoucy As the rules are unpublished, they then need to be re-published to be working in the environment again.

2020-09-22 20:52 UTC, GabrielFG commented on src/Compliance.Package/set_duplicaterule_publishstate.ps1
> +﻿Param(
Didn't know that existed. Will do.

2020-09-22 20:54 UTC, GabrielFG commented on src/Compliance.Solution/Data/Lookups/data.xml
> +        <field name="ownerid" value="a5d21787-0ed1-ea11-a813-000d3a0c5524" lookupentity="systemuser" lookupentityname="Package Deployer" />
I'm not sure how that happened, must be when publishing the package through the pipeline. I'll see what I can do to revert this.

2020-09-22 20:56 UTC, GabrielFG commented on azure-pipelines/unpack-commit-solution-data.yml
> +  condition: always()
or do you mean the condition? The condition makes sure the duplicate rules will get republished even if the the package import fails.

2020-09-22 21:12 UTC, GabrielFG commented on src/Compliance.Solution/Data/Lookups/data.xml
> +    <m2mrelationships />
@pierluc-ssoucy  Some missing relationships here. Is this normal?

2020-09-22 21:14 UTC, GabrielFG commented on src/Compliance.Solution/Data/Lookups/data.xml
> +        <field name="ownerid" value="a5d21787-0ed1-ea11-a813-000d3a0c5524" lookupentity="systemuser" lookupentityname="Package Deployer" />
Changed them back with a search and replace, still not sure the reasoning behind this owner change though.

2020-09-23 12:01 UTC, pierluc-ssoucy commented on src/Compliance.Solution/Data/Lookups/data.xml
> +    <m2mrelationships />
good catch, i missed this. The schema seems fine though, I guess you don't have the data for some reason

2020-09-23 12:42 UTC, joshcampbell191 commented on src/Compliance.Solution/Data/Lookups/data.xml
> +    <m2mrelationships />
Try resetting your environment to see if that fixes the problem.

2020-09-23 20:40 UTC, pierluc-ssoucy approved these changes

2020-09-23 20:45 UTC, merged