Features/complainant tracking
opc-cpvp/OPC.PowerApps pull request #113
Opened 2020-10-07 17:53 UTC by StephBrouil

2020-10-08 01:20 UTC, joshcampbell191 commented
@StephBrouil be sure to checkout the build error when you have the chance.

2020-10-08 17:34 UTC, pierluc-ssoucy requested changes

2020-10-08 17:34 UTC, pierluc-ssoucy commented on src/Compliance.Solution/Solution/Entities/opc_complaint/FormXml/main/{b8bed16c-fe15-4801-ae58-2636ceecce77}.xml
> +                        <control id="opc_complainantperceivedpriority" classid="{3EF39988-22BB-4F0B-BBBE-64B5A3748AEE}" datafieldname="opc_complainantperceivedpriority" disabled="false" />
as discussed with Laurence, we should switch this to a mutliselect.

2020-10-23 12:55 UTC, pierluc-ssoucy commented on src/Compliance.Solution/Solution/Entities/opc_complaint/Entity.xml
> +            <Description description="" languagecode="1033" />
@StephBrouil Je crois que c'est la seul chose qui manque maintenant.

2020-10-30 14:31 UTC, pierluc-ssoucy approved these changes

2020-10-30 14:31 UTC, merged