features/eslint - TypeScript Linting
opc-cpvp/OPC.PowerApps pull request #114
Opened 2020-10-08 02:04 UTC by joshcampbell191

#### This PR accomplishes the following items:
- Introduces [prettier](https://prettier.io/): Opinionated Code Formatter
  - Configurations can be found here:
    - [.prettierrc.json](https://github.com/opc-cpvp/OPC.PowerApps/blob/features/eslint/src/Compliance.WebResources/.prettierrc.json)
    - [.prettierignore](https://github.com/opc-cpvp/OPC.PowerApps/blob/features/eslint/src/Compliance.WebResources/.prettierignore)
- Introduces [eslint](https://eslint.org/): Find and fix problems in your JavaScript code
  - Configurations can be found here:
    - [.eslintrc.json](https://github.com/opc-cpvp/OPC.PowerApps/blob/features/eslint/src/Compliance.WebResources/.eslintrc.json)
    - [.eslintignore](https://github.com/opc-cpvp/OPC.PowerApps/blob/features/eslint/src/Compliance.WebResources/.eslintignore)
  - Also includes [typescript-eslint](https://github.com/typescript-eslint/typescript-eslint): Additional rules / overrides for eslint to provide compatibility with TypeScript
- Introduces [husky](https://github.com/typicode/husky) + [lint-staged](https://github.com/okonet/lint-staged): Allows for running the linter on pre-commits
  - Configurations can be found here:
    - [.huskyrc.json](https://github.com/opc-cpvp/OPC.PowerApps/blob/features/eslint/src/Compliance.WebResources/.huskyrc.json)
    - [.lintstagedrc.json](https://github.com/opc-cpvp/OPC.PowerApps/blob/features/eslint/src/Compliance.WebResources/.lintstagedrc.json)
- Introduces [GitHub Actions](https://github.com/features/actions): Allows for running the linter on pushes and pull requests to master.
  - Configurations can be found here:
    - [linter.yml](https://github.com/opc-cpvp/OPC.PowerApps/blob/features/eslint/.github/workflows/linter.yml)

#### Notes:
- The bulk of the changes were applied using automated fixes from eslint + prettier.
- In some cases, unit tests had to be refactored in order to become compliant with eslint + prettier.
- Some exceptions were added for eslint in the following cases:
  - Implementing an interface from an auto-generated / external source.
  - A known issue has been identified in GitHub against eslint / typescript-eslint.

2020-10-13 15:18 UTC, pierluc-ssoucy requested changes
Other than the comments below, there is the on-going debate one-liner if statement going-on.

2020-10-13 15:18 UTC, pierluc-ssoucy commented on src/Compliance.WebResources/src/dialogs/Templates/TemplateDialog.ts
>              };
I think in those situations, loginHint should param name should still appear.

2020-10-14 15:36 UTC, joshcampbell191 commented on src/Compliance.WebResources/src/dialogs/Templates/TemplateDialog.ts
>              };
Updated the eslint rules for object-shorthand to handle this.

2020-10-14 15:38 UTC, joshcampbell191 commented on src/Compliance.WebResources/src/dialogs/Templates/TemplateDialog.test.ts
> +
`void` is used to explicitly ignore the Promise returned by i18next.init. Otherwise, we'd have to add code that either awaits or handles the exceptions by adding `then` / `catch`.

2020-10-14 15:39 UTC, joshcampbell191 commented on src/Compliance.WebResources/src/controls/Checklist/ChecklistControl.ts
> +                >`;
This is as close as we can get to properly formatting the HTML unless we change to another framework (`react` or `lit-html`) for these components in the future.

2020-10-14 15:40 UTC, joshcampbell191 commented on src/Compliance.WebResources/src/services/RiskAssessmentService.ts
> +    > {
Added prettier exceptions to properly format code block.

2020-10-14 15:40 UTC, joshcampbell191 commented on src/Compliance.WebResources/src/interfaces.ts
> +} & { opc_respondentrepresentative: Contact_Result } & { opc_respondentlegalrepresentative: Contact_Result };
Added prettier exceptions to properly format code block.

2020-10-14 15:40 UTC, joshcampbell191 commented on src/Compliance.WebResources/src/interfaces.ts
> +    >;
Added prettier exceptions to properly format code block.

2020-10-14 15:40 UTC, joshcampbell191 commented on src/Compliance.WebResources/src/controls/RiskAssessment/RiskAssessmentControl.test.ts
> +                } & { opc_isselected: boolean })[] = [
Added prettier exceptions to properly format code block.

2020-10-14 15:41 UTC, joshcampbell191 commented on src/Compliance.WebResources/src/controls/RiskAssessment/RiskAssessmentControl.test.ts
> +        const riskAppetites: (opc_RiskAppetite_Fixed & { opc_riskappetiteid: string } & { opc_name: string } & { opc_value: number })[] = [
Added prettier exceptions to properly format code block.

2020-10-14 15:41 UTC, joshcampbell191 commented on src/Compliance.WebResources/src/controls/RiskAssessment/RiskAssessmentControl.test.ts
> +    } & { opc_isselected: boolean } {
Added prettier exceptions to properly format code block.

2020-10-14 18:18 UTC, pierluc-ssoucy approved these changes

2020-10-14 18:50 UTC, merged