Update Solution - Compliance: document classification environment var…
opc-cpvp/OPC.PowerApps pull request #119
Opened 2020-10-27 03:40 UTC by mitchkirady

- Create Environment variable to store document structure (JSON) for Complaints and Allegations.
- Create flows to set document structure on Complaints and Allegations (Access).
- Add "Reference Number" to quick create form on Allegation entity.
- Create "All SharePoint Documents Grid" to display SharePoint document structure on Complaint form.
- Increase "Name" field in "Industry" entity to 146 characters (for industry #56 to be included).

Although the solution includes connection reference for SharePoint, flows which use the SharePoint connector will need to be Edit to set the connection before turning on the flow.

2020-10-27 21:02 UTC, pierluc-ssoucy requested changes

2020-10-27 23:26 UTC, mitchkirady commented on src/Compliance.Solution/Solution/Workflows/Allegation-CreateUpdate-DocumentsClassification-A662FCC0-7312-EB11-A813-000D3A0C3110.json
> +{
Makes sense. This is resolved in the next commit.

2020-10-27 23:32 UTC, mitchkirady commented on src/Compliance.Solution/Solution/Other/Customizations.xml
> +    <connectionreference connectionreferencelogicalname="opc_sharedcommondataserviceforapps_3689c">
I removed two extra connection references for CDS, since they aren't used. You need to setup the SharePoint connection reference in your new environment before being able to activate the flows (whether it's a single flow or in bulk).

2020-10-27 23:56 UTC, mitchkirady commented on src/Compliance.Solution/Solution/Entities/SharePointDocument/SavedQueries/{ad6cbebe-6b0d-eb11-a813-000d3af43a22}.xml
> +﻿<?xml version="1.0" encoding="utf-8"?>
Looks like you just found one of the disadvantages of using a custom sub-grid to show SharePoint documents, instead of using the out-of-box solution. A workaround is to click on the "Document Location" button and select the Complaint's document location to get back to the root folder for that complaint. Otherwise, using the out-of-box solution wouldn't have this limitation, but we'd have to navigate to the "Related" tab, and select "Documents" from there. Both solutions aren't ideal, but the current one is probably better for usability until the out-of-box solution is available as a tab on custom entities.

2020-10-29 12:54 UTC, pierluc-ssoucy commented on src/Compliance.Solution/Solution/Entities/SharePointDocument/SavedQueries/{ad6cbebe-6b0d-eb11-a813-000d3af43a22}.xml
> +﻿<?xml version="1.0" encoding="utf-8"?>
@mitchkirady understood. Could you give a quick try at the drag and drop enabled on the pcf gallery see if it resolves that issue.

2020-10-29 13:10 UTC, mitchkirady commented on src/Compliance.Solution/Solution/Entities/SharePointDocument/SavedQueries/{ad6cbebe-6b0d-eb11-a813-000d3af43a22}.xml
> +﻿<?xml version="1.0" encoding="utf-8"?>
just looked into the details and sent you some info, which make this solution not good for us.

2020-10-30 20:10 UTC, closed without merging