Features/checklist templates
opc-cpvp/OPC.PowerApps pull request #121
Opened 2020-11-03 20:42 UTC by Sargatos

- Modified Question Template entity and added two new fields.
- Modified ChecklistControl to display and save: Select, Multiselect, Date, Number, Calculated field.
- Modified Template Dialog code to retrieve and save the associated allegations.
- Added test for all of this
- [PBI 543](https://dev.azure.com/opc-cpvp/O365%20Cloud/_workitems/edit/543)

- Seed data has not been done. We might wait until it's moved to issues instead of allegations? (the new field of Question Template are already added to the lookup_schema.xml file)

2020-11-09 17:30 UTC, GabrielFG requested changes
As discussed with you Jo, I am not done with the PR but here's some stuff you can work on in the meantime.

2020-11-09 17:30 UTC, GabrielFG commented on src/Compliance.WebResources/src/controls/Checklist/ChecklistControl.ts
> +                cr.opc_response = `${dateValues.groups.month}/${dateValues.groups.date}/${dateValues.groups.year}`;
Consider formatting to year/month/day

2020-11-09 17:30 UTC, GabrielFG commented on src/Compliance.WebResources/src/helpers/JQueryHelper.ts
> +                $(".multiselect-container.dropdown-menu.show").removeClass("show");
Consider documenting this section some more as it can be confusing.

2020-11-10 15:11 UTC, GabrielFG commented on src/Compliance.WebResources/src/dialogs/Templates/TemplateDialog.ts
> +                const promiseArray: [Promise<ComplaintWithRelationships>, Promise<string>, Promise<string>, Promise<any>] = [
Instead of the "any" type for the last promise, switch to 'AllegationWithChecklistResponse[]" unless there was some reason not to do it.

2020-11-10 15:30 UTC, Sargatos commented on src/Compliance.WebResources/src/controls/Checklist/ChecklistControl.ts
> +                cr.opc_response = `${dateValues.groups.month}/${dateValues.groups.date}/${dateValues.groups.year}`;
What I am doing instead is format it with "default" as the locale so it takes what the browser is using and specified "UTC" as the timezone so that the date don't change.

2020-11-10 15:30 UTC, Sargatos commented on src/Compliance.WebResources/src/dialogs/Templates/TemplateDialog.ts
> +                const promiseArray: [Promise<ComplaintWithRelationships>, Promise<string>, Promise<string>, Promise<any>] = [
Nope, must have missed it. Thanks!

2020-11-10 21:12 UTC, Sargatos commented on src/Compliance.WebResources/src/helpers/JQueryHelper.ts
> +                $(".multiselect-container.dropdown-menu.show").removeClass("show");
It should be way better now.

2020-11-12 17:45 UTC, pierluc-ssoucy requested changes
Very nice. Comments are mostly regarding documentation/code commenting.

One other suggestion for the questions for TLs... We may want to rephrase "What final response did the respondent issue?" to something like "Did the respondent issue a response or a commitment to respond?"

2020-11-16 21:06 UTC, Sargatos commented on src/Compliance.WebResources/src/controls/Checklist/ChecklistControl.ts
> +        }
- StringHelper and DateHelper would make sense since they will likely be reused elsewhere.
- I'm not sure where I would put the calculate method. CalculatedFieldHelper?

2020-11-20 21:11 UTC, pierluc-ssoucy approved these changes
Approved with one comment, i'll leave it up to you to decide if you want to fix it in a separate PR or not.

2020-11-25 21:39 UTC, pierluc-ssoucy approved these changes
Victoire.

2020-12-03 14:48 UTC, GabrielFG approved these changes
lgtm

2020-12-03 14:48 UTC, merged