Features/sla intake er
opc-cpvp/OPC.PowerApps pull request #122
Opened 2020-11-19 22:32 UTC by mitchkirady

PBI 118 (Intake Processing SLA) and PBI 563 (ER SLA Notifications)
- Add SLA Date to Complaint form header (read-only)
- Add Source field to Complaint and form
- Add processes to set SLA Date for Triage/Intake and ER
- Add process to clear SLA Date on arrival into ER and Investigations
- Add daily flow for ER notification to ER Managers on SLA Date passed
- Add views for SLA Date (all milestones + Intake Processing only)
- Add chart for SLA (all milestones)
- Add chart to CIRD Dashboard

2020-11-20 15:40 UTC, Sargatos commented on src/Compliance.Solution/Solution/Other/Solution.xml
> -      <RootComponent type="381" id="{4710a2e7-53cc-ea11-a812-000d3af46489}" behavior="0" />
Apparently this is normal now.

2020-11-20 17:02 UTC, Sargatos reviewed
I didn't really find any issue. Maybe comments and questions.

- Only 4 fields can be displayed in the header apparently. Status Reason and Owner are now hidden but can still be accessed by clicking the arrow next to the SLA date. I don't really mind, I just wanted to point it out. Maybe we'll want to move or hide some fields someday.

- Why are some new workflows of type "Flow" and others of type "Process"? Is it because some of them run in the background and others don't?

2020-11-20 17:47 UTC, mitchkirady commented
@Sargatos 
- 4 fields show up in the header, but others can be accessed via fly-out form. I don't see any issues with that, but thanks for pointing it out.
- That's correct, synchronous processes still need to be created as classic workflows. Asynch processes use Power Automate.

2020-11-20 22:10 UTC, pierluc-ssoucy requested changes

2020-11-23 01:31 UTC, mitchkirady commented on src/Compliance.Solution/Solution/Workflows/Complaint-CreateUpdate-SetIntakeProcessingSLA-74BA29AD-5823-EB11-A813-000D3A0C26F9.json
> +{
Good point, I fogot about that one. Added "Complaint Received Date" because that name is more aligned with our other date fields. Thanks.

2020-11-23 16:03 UTC, pierluc-ssoucy commented on src/Compliance.Solution/Solution/Workflows/Complaint-CreateUpdate-SetIntakeProcessingSLA-74BA29AD-5823-EB11-A813-000D3A0C26F9.json
> +{
Could we set the default value to be the created date.

2020-11-23 18:12 UTC, mitchkirady commented on src/Compliance.Solution/Solution/Workflows/Complaint-CreateUpdate-SetIntakeProcessingSLA-74BA29AD-5823-EB11-A813-000D3A0C26F9.json
> +{
I see two options for this:
- Workflow runs on save, and sets the date to today if the field is empty
- Add typescript to set the default to the current date.

2020-11-23 18:36 UTC, mitchkirady commented on src/Compliance.Solution/Solution/Workflows/Complaint-CreateUpdate-SetIntakeProcessingSLA-74BA29AD-5823-EB11-A813-000D3A0C26F9.json
> +{
@pierluc-ssoucy to add TS, to set default date to today

2020-11-23 19:51 UTC, pierluc-ssoucy approved these changes

2020-11-23 19:59 UTC, merged