Features/contact accessrequest
opc-cpvp/OPC.PowerApps pull request #126
Opened 2021-01-07 14:20 UTC by StephBrouil

- Added access request number field when Allegation type is "Access" for Issue and Allegation in Main and Quick Create forms
- Limited access request field to 20 characters
- Added Contact lookup field in Issue main form 
- Filtered contact fields by respondents contacts
- Connected Issue main and quick create forms and Allegation quick create form
- Added tests for Access Request number visibility in both forms in Allegation and Issue.

2021-01-07 19:26 UTC, pierluc-ssoucy requested changes

2021-01-07 19:26 UTC, pierluc-ssoucy commented on src/Compliance.WebResources/src/forms/AllegationMainForm.test.ts
> +        });
why is this skipped?

2021-01-07 21:35 UTC, joshcampbell191 commented on src/CrmSvcUtil.Filter/CrmSvcUtil.Filter.csproj
>        <HintPath>..\packages\Microsoft.CrmSdk.CoreTools.9.1.0.51\content\bin\coretools\CrmSvcUtil.exe</HintPath>
The HintPath to `Microsoft.CrmSdk.CoreTools` should also be updated to `9.1.0.64`.

2021-01-07 21:35 UTC, joshcampbell191 commented on src/CrmSvcUtil.Filter/CrmSvcUtil.Filter.csproj
>        <HintPath>..\packages\Microsoft.CrmSdk.CoreTools.9.1.0.26\content\bin\coretools\Microsoft.Xrm.Tooling.Ui.Styles.dll</HintPath>
The HintPath to `Microsoft.CrmSdk.CoreTools` should also be updated to `9.1.0.64`.

2021-01-08 19:50 UTC, StephBrouil commented on src/Compliance.WebResources/src/forms/AllegationMainForm.ts
> +
I disabled the field by default but we still need to check that the allegation type value exists to hide the reference number in case it's removed.

2021-01-08 21:01 UTC, StephBrouil commented on src/Compliance.WebResources/src/forms/AllegationQuickCreateForm.ts
> +    }
Same as above.

2021-01-08 21:02 UTC, StephBrouil commented on src/Compliance.WebResources/src/forms/IssueMainForm.ts
> +            }
Same as in Allegation.

2021-01-08 21:02 UTC, StephBrouil commented on src/Compliance.WebResources/src/forms/IssueQuickCreateForm.ts
> +            }
Same as in Allegation.

2021-01-11 15:57 UTC, pierluc-ssoucy requested changes

2021-01-11 15:57 UTC, pierluc-ssoucy commented on src/Compliance.WebResources/src/forms/AllegationMainForm.ts
> +            const isReferenceNumberVisible = allegationTypeValue && allegationTypeValue[0].name === "Access";
Should have caught that in the first review. But we should probably be comparing to the GUID here as this won't work in with french.

2021-01-11 15:57 UTC, pierluc-ssoucy commented on src/Compliance.WebResources/src/forms/IssueQuickCreateForm.ts
> +            const isAccessRequestNumberVisible = allegationTypeValue && allegationTypeValue[0].name === "Access";
same thing here, we probably want to use the GUID.

2021-01-12 20:59 UTC, pierluc-ssoucy approved these changes

2021-01-12 20:59 UTC, merged