Update Solution - Compliance: PBI 540 148 143
opc-cpvp/OPC.PowerApps pull request #127
Opened 2021-01-12 02:39 UTC by mitchkirady

Complaints entity:
- End-to-end ER Process (Individual Complaint BPF)
- Complaint dispositions, Status reasons, close reasons
- Workflows and notifications for assignment to ER Officer, Report Redactor, ER Backlog team, and ER Review team
- Close notifications
- Routing (replaced asynchronous flow by synchronous workflow)

Issues entity:
- Disposition + Last Milestone at Disposition

Misc:
- Increase filed length for Event entity to bypass plugin errors

2021-01-13 21:48 UTC, pierluc-ssoucy requested changes
Did a first round of review, which did not includes bpf or workflows. Once the other issues are fixed could you republish to a sandbox and i'll verify those. @joshcampbell191 or @Sargatos will also be making the associated TS changes when time permits.

2021-01-13 21:48 UTC, pierluc-ssoucy commented on src/Compliance.Solution/Solution/Entities/opc_complaint/Entity.xml
> +        </attribute>
this name might be slightly confusing as we'll likely have another approval for investigation later.

2021-01-13 21:48 UTC, pierluc-ssoucy commented on src/Compliance.Solution/Solution/Entities/opc_complaint/Entity.xml
> +        <attribute PhysicalName="opc_closingletterorsummaryrfsent">
we already had a field named opc_sentcloseletter. We probably should probably keep one of them.

2021-01-13 21:48 UTC, pierluc-ssoucy commented on src/Compliance.Solution/Solution/OptionSets/opc_complaintapproval.xml
> +</optionset>
Maybe we should rename here, given the approval is actually for the er disposition.

2021-01-13 21:48 UTC, pierluc-ssoucy commented on src/Compliance.Solution/Solution/OptionSets/opc_issuedisposition.xml
> +  </options>
the (RF) were only notes for myself as i was looking through it, they are not required. apologies!

2021-01-13 21:48 UTC, pierluc-ssoucy commented on src/Compliance.Solution/Solution/Roles/Compliance - Early Resolution Backlog Team.xml
> +</Role>
This should not be included.

2021-01-13 21:48 UTC, pierluc-ssoucy commented on src/Compliance.Solution/Solution/Roles/Compliance - Early Resolution Review Team.xml
> +</Role>
This should not be included.

2021-01-13 21:48 UTC, pierluc-ssoucy commented on src/Compliance.Solution/Solution/Workflows/IndividualComplaint-CreateUpdate-SetStatusReasonfo-66EF3F32-9DDC-4B79-9ACD-685CB6DD07FA.xaml.data.xml
> +  <Subprocess>1</Subprocess>
What purpose does this serve?

2021-01-15 01:05 UTC, mitchkirady commented on src/Compliance.Solution/Solution/Entities/opc_complaint/Entity.xml
> +        </attribute>
Used "ER Approval" instead, but kept "Approval" in the BPF since the context is within ER.

2021-01-15 01:11 UTC, mitchkirady commented on src/Compliance.Solution/Solution/Entities/opc_complaint/Entity.xml
> +        <attribute PhysicalName="opc_closingletterorsummaryrfsent">
Replaced by "opc_sendcloseletter".

2021-01-15 01:12 UTC, mitchkirady commented on src/Compliance.Solution/Solution/OptionSets/opc_complaintapproval.xml
> +</optionset>
Replaced by "ER Approval" (opc_erapproval) with same values.

2021-01-15 01:15 UTC, mitchkirady commented on src/Compliance.Solution/Solution/OptionSets/opc_issuedisposition.xml
> +  </options>
haha ok - I removed the "RF". Should "Settled" include "(investigation only with settlement)" or should that be removed too?

2021-01-15 01:19 UTC, mitchkirady commented on src/Compliance.Solution/Solution/Roles/Compliance - Early Resolution Backlog Team.xml
> +</Role>
During the ER process, the "Early Resolution Backlog Team" gets assigned the complaint when no ER Officer is specified. If the team doesn't have this security role, there will be an error in the BPF. Which security roles will they have?

2021-01-15 01:19 UTC, mitchkirady commented on src/Compliance.Solution/Solution/Roles/Compliance - Early Resolution Review Team.xml
> +</Role>
During the ER process, the "Early Resolution Review Team" gets assigned the complaint when it's time to Approve it. If the team doesn't have this security role, there will be an error in the BPF. Which security roles will they have?

2021-01-15 01:40 UTC, mitchkirady commented on src/Compliance.Solution/Solution/Workflows/IndividualComplaint-CreateUpdate-SetStatusReasonfo-66EF3F32-9DDC-4B79-9ACD-685CB6DD07FA.xaml.data.xml
> +  <Subprocess>1</Subprocess>
That's to enable the workflow to run as a "Child workflow". Although it does no harm, I'm not sure why this was enabled, so I've disabled it.

2021-01-15 15:36 UTC, pierluc-ssoucy commented on src/Compliance.Solution/Solution/OptionSets/opc_issuedisposition.xml
> +  </options>
removed as well :)

2021-01-15 15:41 UTC, pierluc-ssoucy commented on src/Compliance.Solution/Solution/Roles/Compliance - Early Resolution Backlog Team.xml
> +</Role>
I thought we were going to-reuse the existing roles?

2021-01-15 18:35 UTC, mitchkirady commented on src/Compliance.Solution/Solution/Roles/Compliance - Early Resolution Backlog Team.xml
> +</Role>
As discussed, ER Backlog team will have ER Officer role

2021-01-15 18:36 UTC, mitchkirady commented on src/Compliance.Solution/Solution/Roles/Compliance - Early Resolution Review Team.xml
> +</Role>
As discussed, ER Review team will have ER Manager role

2021-01-20 22:04 UTC, pierluc-ssoucy approved these changes

2021-01-20 22:04 UTC, pierluc-ssoucy commented on src/Compliance.Solution/Solution/Entities/opc_issue/FormXml/main/{ba934036-d2cc-49ff-967b-733f288a46b6}.xml
> +                        <control id="header_opc_disposition" classid="{3EF39988-22BB-4F0B-BBBE-64B5A3748AEE}" datafieldname="opc_disposition" disabled="false" />
Just making note that this should likely be filtered later on, as some of the disposition only apply when the issue is at investigation.

2021-01-20 22:04 UTC, merged