Features/provisions entity
opc-cpvp/OPC.PowerApps pull request #133
Opened 2021-02-08 22:23 UTC by GabrielFG

Added provisions entity and it's seed data and extra JavaScript logic for the issue form.

- The primary utility Will be able to tag issues with provisions (laws) on the issues form with an incoming custom PCF.
- JavaScript was added to the issues form to dynamically change the view of the provisions PCF based on the parent records' legislation.

How that will look once the PCF is published (PA legislation): 
![image](https://user-images.githubusercontent.com/6852285/107269800-1dffe100-6a18-11eb-86dc-d1a4a901d731.png)

2021-02-15 19:23 UTC, Sargatos reviewed
It looks good. I just have a couple of comments.

2021-02-15 19:23 UTC, Sargatos commented on src/Compliance.WebResources/src/forms/IssueMainForm.test.ts
> +                        entityType: "1039",
What is entityType 1039? Is there an enum for this or maybe putting a comment?

2021-02-15 19:23 UTC, Sargatos commented on src/Compliance.WebResources/src/forms/IssueMainForm.test.ts
> +            control.getViewSelector().getCurrentView().name.should.equal("Active PA Provisions");
Should there also be a test for PIPEDA? Not sure just asking.

2021-02-15 19:47 UTC, GabrielFG commented on src/Compliance.Solution/Data/Lookups/data_schema.xml
> -  <entity name="team" displayname="Team" etc="9" primaryidfield="teamid" primarynamefield="name" disableplugins="false">
hmm bizarre, je ne penses pas non.. Je vais le rajouter.

2021-02-15 19:54 UTC, GabrielFG commented on src/Compliance.WebResources/src/forms/IssueMainForm.test.ts
> +                        entityType: "1039",
No enums for this but like in the IssueForm, I will add a comment indicating it's a SavedQuery.

2021-02-15 19:56 UTC, GabrielFG commented on src/Compliance.WebResources/src/forms/IssueMainForm.test.ts
> +            control.getViewSelector().getCurrentView().name.should.equal("Active PA Provisions");
I'm not 100% sure as the logic is just the same but as inverse to the PA test but I would put PIPEDA as the acronym instead. What do you think is best practice?

2021-02-15 20:40 UTC, Sargatos commented on src/Compliance.WebResources/src/forms/IssueMainForm.test.ts
> +            control.getViewSelector().getCurrentView().name.should.equal("Active PA Provisions");
I think we already have some tests that does something similar. It might be safer in case some error happens only under one condition.

2021-03-04 21:02 UTC, pierluc-ssoucy requested changes

2021-03-05 21:43 UTC, GabrielFG commented on src/Compliance.WebResources/src/forms/IssueMainForm.test.ts
> +                        entityType: "1039", // SavedQuery
The entity type code has not changed in a while (https://spandcrm.com/2017/08/14/dynamics-365-entity-type-code-list/) but I will check a bit further if there's a cleaner way to reference this.

2021-03-05 21:49 UTC, GabrielFG commented on src/Compliance.WebResources/src/forms/IssueMainForm.ts
> +            await this.setComplaint(formContext).catch(e => console.error("error setting complaint", e));
I meant that the TODO probably should not be actioned anymore as the Complaint property is now also used for the setProvisionsView method and not only for the search. I can just remove that TODO comment if that's fine with you.

2021-03-08 15:38 UTC, GabrielFG commented on src/Compliance.WebResources/src/forms/IssueMainForm.test.ts
> +                        entityType: "1039", // SavedQuery
Switched to enum.

2021-03-08 20:51 UTC, GabrielFG commented on src/Compliance.WebResources/src/forms/IssueMainForm.test.ts
> +                        entityType: "1039", // SavedQuery
Might might not be important. I'll test out other entity codes.

2021-03-09 16:43 UTC, GabrielFG commented on src/Compliance.WebResources/src/forms/IssueMainForm.test.ts
> +                        entityType: "1039", // SavedQuery
Tested it out, does not seem to be important but it's still a required field so it still needs to be set. Microsoft docs says to either put the SavedQuery code or UserQuery: https://docs.microsoft.com/en-us/powerapps/developer/model-driven-apps/clientapi/reference/grids/viewselector/setcurrentview

2021-03-11 13:30 UTC, pierluc-ssoucy approved these changes
I noticed that in the seed data, the first provision node refers to a parent, so unsure how that is going to behave when importing.

2021-03-15 20:31 UTC, merged