Features/jurisdiction
opc-cpvp/OPC.PowerApps pull request #135
Opened 2021-02-12 02:04 UTC by mitchkirady

PBI 566:
- Add intersect table between Legislation and Allegation Type
- Add N:N relationship between Allegation Type and Checklist Type
- Add Description field to Allegation Type (for multi-lingual plugin)
- Add Personal Information Type table
- Add lookup to Personal Information Type table from Allegation
- Add new configuration data and update existing
- Update Cloud Flow to generate one or multiple checklists based on Allegation Type

2021-02-17 15:17 UTC, Sargatos reviewed
Here's what I got so far. I haven't tested everything in the environment yet.

Also, I'm getting an error from Multilanguage plugin when I try to create a new Legislation/Allegation Type. It's complaining because there is no value in the english/french fields. Since it doesn't look like it is being used, should this be not localizable?

2021-02-24 20:00 UTC, Sargatos commented on src/Compliance.Solution/Solution/Other/Relationships/opc_allegationtype.xml
> +  <EntityRelationship Name="opc_allegationtype_legislation_allegationtype">
I still think the name is wrong. Is it because there is not enough space to write it in full?

2021-02-24 20:01 UTC, Sargatos commented on src/Compliance.Solution/Solution/Other/Relationships/opc_legislation.xml
> +  <EntityRelationship Name="opc_legislation_allegationtypes_leglislation">
Same comment as the other relationship.

2021-02-24 20:13 UTC, Sargatos commented
> Also, I'm getting an error from Multilanguage plugin when I try to create a new Legislation/Allegation Type. It's complaining because there is no value in the english/french fields. Since it doesn't look like it is being used, should this be not localizable?

My bad, it is being used. We should probably display the English and French name on the form then. This way we can manually create new entries.

2021-02-24 22:24 UTC, mitchkirady commented on src/Compliance.Solution/Solution/Other/Relationships/opc_allegationtype.xml
> +  <EntityRelationship Name="opc_allegationtype_legislation_allegationtype">
The name was too long, so I had to shorten it but make sure it's still understandable.

2021-02-24 22:30 UTC, mitchkirady commented on src/Compliance.Solution/Solution/Other/Relationships/opc_legislation.xml
> +  <EntityRelationship Name="opc_legislation_allegationtypes_leglislation">
Same comment - The name was too long, so I had to shorten it but make sure it's still understandable.

2021-03-01 22:33 UTC, pierluc-ssoucy requested changes

2021-03-01 22:33 UTC, pierluc-ssoucy commented on src/Compliance.Solution/Data/Lookups/data_schema.xml
> +      <field displayname="Leglislation" name="opc_leglislation" type="entityreference" lookupType="opc_legislation" customfield="true" />
typo here.

2021-03-01 22:33 UTC, pierluc-ssoucy commented on src/Compliance.Solution/Solution/Entities/opc_legislationallegationtype/Entity.xml
> +        <attribute PhysicalName="opc_leglislation">
typo in the field name here. This also affects the relationship and the seed data.

2021-03-01 22:33 UTC, pierluc-ssoucy commented on src/Compliance.Solution/Solution/Entities/opc_legislationallegationtype/FormXml/quick/{a0d3ecb5-0cd3-4964-b037-6914ab2327e6}.xml
> +<forms xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
This does not seem to be used. Likely missing from site map. I am not sure if its by default, but we should make sure the allegation type is preselected when lunched from the allegation type form.

2021-03-01 22:33 UTC, pierluc-ssoucy commented on src/Compliance.Solution/Data/Lookups/data.xml
> +  <entity name="opc_personalinformationtype" displayname="Personal Information Type">
Not a huge issue, but we may want to remove the letter prefix as this will be used with pipeda as well. To be confirmed by Laurence.

2021-03-01 22:33 UTC, pierluc-ssoucy commented on src/Compliance.Solution/Solution/Workflows/Allegation-Create-GenerateChecklistbasedontemplate-5D69364A-D857-EA11-A811-000D3AF46CC5.json
> +            "Get_Checklist_Types_for_Legislation_Allegation_Type": {
@mitchkirady Could you create a separate work item (perhaps as a bug) with the details to ensure we don't forget about it.

2021-03-02 21:09 UTC, mitchkirady commented on src/Compliance.Solution/Solution/Entities/opc_legislationallegationtype/FormXml/quick/{a0d3ecb5-0cd3-4964-b037-6914ab2327e6}.xml
> +<forms xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
This is just the quick view form, which comes by default when you create a custom table, no adjustments made since it's not used in our app. I've added the table to our model-driven app though, and also included all the other OPC tables, since they were missing from the app designer. (We should include all tables in the app designer if they are used by our app)

2021-03-02 21:11 UTC, mitchkirady commented on src/Compliance.Solution/Solution/Entities/opc_legislationallegationtype/FormXml/quick/{a0d3ecb5-0cd3-4964-b037-6914ab2327e6}.xml
> +<forms xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
The allegation type is automatically selected when adding it to a legislation. That's taken care of by default in the relationship behavior.

2021-03-03 21:40 UTC, mitchkirady commented on src/Compliance.Solution/Data/Lookups/data.xml
> +  <entity name="opc_personalinformationtype" displayname="Personal Information Type">
Removed the letter per discussion with Laurence. Also replaced personal information lookup by subgrid (tagging PCF) on Allegation form.

2021-03-04 00:34 UTC, mitchkirady reviewed
Addressed all changes:
- Typo on Legislation field
- Remove letter prefix from Personal Information Type data
- Replace Personal Information Type lookup by subgrid on Allegation form

2021-03-04 17:42 UTC, pierluc-ssoucy submitted a review, later dismissed

2021-03-04 17:42 UTC, pierluc-ssoucy commented on src/Compliance.Solution/Solution/Entities/opc_legislationallegationtype/Entity.xml
> +        <attribute PhysicalName="opc_name">
Should we only have this field populated from the workflow automatically + the islocalized field?

2021-03-07 13:14 UTC, mitchkirady commented on src/Compliance.Solution/Solution/Entities/opc_legislationallegationtype/Entity.xml
> +        <attribute PhysicalName="opc_name">
Yes, this is how it's currently setup. We only display the Legislation and Allegation Type fields on the form, and the name is generated based on that, with bilingual capability.

**Form:**
![image](https://user-images.githubusercontent.com/59924895/110241067-dee08500-7f1c-11eb-92fb-06342946ca7d.png)

**English:**
![image](https://user-images.githubusercontent.com/59924895/110241010-9b861680-7f1c-11eb-9065-59837f7e5fa4.png)

**French:**
![image](https://user-images.githubusercontent.com/59924895/110241043-c83a2e00-7f1c-11eb-9adf-53db482eab8d.png)

2021-03-07 13:33 UTC, mitchkirady commented on src/Compliance.Solution/Solution/Other/Relationships/BookableResourceBooking.xml
> +﻿<?xml version="1.0" encoding="utf-8"?>
Somehow the PR environment had D365 apps installed. I deployed the build to a Power Apps environment. These are now removed.

2021-03-07 13:35 UTC, mitchkirady commented on src/Compliance.Solution/Solution/Entities/opc_allegation/FormXml/main/{5d39077d-dd2b-4b2e-a6b4-a534abf85ef8}.xml
> +                        </control>
@joshcampbell191 - I created bug 888 for this item.

2021-03-07 13:53 UTC, mitchkirady reviewed
changes addressed.

2021-03-08 19:34 UTC, pierluc-ssoucy approved these changes

2021-03-08 19:35 UTC, merged