Features/allegation ribbon
opc-cpvp/OPC.PowerApps pull request #137
Opened 2021-03-09 18:50 UTC by StephBrouil

**PBI 556/569**

-Added button in Complaint and Allegation ribbons to create new reminder.
   -Added custom query to verify that the complaint contains an Access allegation to enable button.
-Added button in Allegation and Allegation grid to associate an issue with an allegation.
   -Added custom query to verify that the allegation grid has an Allegation with acceptable disposition selected to enable button.
-Defined enable rules for buttons in Complaint and Allegation ribbons.
-Added separate command handlers for buttons (New reminder from Allegation and from complaint, Associate issue from Allegation and Allegation grid)
-Added tests for all command handlers
-Added parameter to query dispatcher to get selectedItemsIds in Allegation grid.
-Added many to many relationship between Allegation and Issue
-Added StringHelper to remove brackets from guids and changed Allegation Type enum to guid with no brackets.
   -Implemented the changes in both forms for Allegation and Issue.
-Added AllegationType service
-In Allegation service 
   -Added function to get an allegation with it's issues, and added the type AllegationWithIssues
   -Added an update to associate an Allegation with an Issue
-Added grid and gridrow mocks for testing framework

2021-03-11 20:25 UTC, pierluc-ssoucy requested changes

2021-03-11 20:25 UTC, pierluc-ssoucy commented on src/Compliance.WebResources/src/handlers/Commands/OpenReminderQuickCreateFromAllegationFormCommandHandler.ts
> +        }
this is probably something that should be tested.

2021-03-11 20:25 UTC, pierluc-ssoucy commented on src/Compliance.WebResources/src/handlers/Commands/OpenReminderQuickCreateFromAllegationFormCommandHandler.ts
> +            this._xrmNavigation.openForm(entityFormOptions, this._reminderParameters).then(() => {});
I am not 100% certain, but I don't think you need the then if nothing is done with it.

2021-03-11 20:25 UTC, pierluc-ssoucy commented on src/Compliance.WebResources/src/handlers/Commands/OpenReminderQuickCreateFromComplaintFormCommandHandler.ts
> +            this._xrmNavigation.openForm(entityFormOptions, this._reminderParameters).then(() => {});
I am not 100% certain, but I don't think you need the then if nothing is done with it.

2021-03-15 13:32 UTC, StephBrouil commented on src/Compliance.WebResources/src/helpers/StringHelper.ts
> +        const regex = new RegExp("^{?(.*?)}$");
I removed the ? on the curly as I left it there by accident. I just tested it and it works without escaping.

2021-03-15 15:15 UTC, StephBrouil commented on src/Compliance.Solution/Solution/Entities/opc_complaint/RibbonDiff.xml
> +      </EnableRule>
The enable rule is now removed along with the query handler.

2021-03-15 15:47 UTC, StephBrouil commented on src/Compliance.WebResources/src/handlers/Commands/OpenReminderQuickCreateFromAllegationFormCommandHandler.ts
> +            this._xrmNavigation.openForm(entityFormOptions, this._reminderParameters).then(() => {});
This was added to avoid @typescript-eslint/no-floating-promises linting error

2021-03-15 15:47 UTC, StephBrouil commented on src/Compliance.WebResources/src/handlers/Commands/OpenReminderQuickCreateFromComplaintFormCommandHandler.ts
> +            this._xrmNavigation.openForm(entityFormOptions, this._reminderParameters).then(() => {});
This was added to avoid @typescript-eslint/no-floating-promises linting error

2021-03-16 12:45 UTC, pierluc-ssoucy commented on src/Compliance.WebResources/src/helpers/StringHelper.ts
> +        const regex = new RegExp("^{?(.*?)}$");
Did you want the method to format the GUID that do not contain the curlys as well?

2021-04-20 14:31 UTC, JonathanThomassin commented on src/Compliance.Solution/Solution/Entities/opc_event/Entity.xml
> +          <Length>800</Length>
Is it normal that the Subject field is now half its length?

2021-04-20 15:21 UTC, JonathanThomassin commented on src/Compliance.WebResources/src/services/AllegationService.ts
> +    }
I'm not sure about this name since it doesn't really update the whole Allegation but instead associate an issue with an allegation.

2021-04-20 15:27 UTC, JonathanThomassin commented on src/Compliance.WebResources/test/XrmGridRowControlMock.ts
> +    // TODO remove INamedComponent implementation which is bound by XrmCollectionMock
Should we do this now or is it more complicated than removing the implement reference?

2021-04-26 17:37 UTC, JonathanThomassin commented on src/Compliance.Solution/Solution/EnvironmentVariables/environment_variable_values.json
> -{
This might not be necessary after merging from master.

2021-04-26 17:46 UTC, JonathanThomassin reviewed
I am not 100% sure what is the wanted behavior of the buttons so some of my comments might not make sense. 
I used this environment to test: https://opc-compliance-ribbons.crm3.dynamics.com/

- "New Reminder" button
  - On the complaint form
    - I think this has been mentionned in a comment on this PR, but I think the "New Reminder" button should always be visible on the ribbon.
    - Also, after I created a new allegation of type Access to display the "new reminder" button, I had to refresh the page to see it. (I dont know if it's an issue or not)
  - On the allegation form
    - After reading Peeth's comments on the PBI, I think this is not supposed to be here , but on the Issue form instead.
  - When I tried to create a reminder using the new ribbon buttons, the association between the reminder and the complaint is not done and I received an error message when I tried to save. (Because Notify Case Owner was selected)
- "Associate New Issue" button
  - The button is available when more than one allegation is selected, but it only creates 1 issue.

2021-05-03 18:11 UTC, StephBrouil commented on src/Compliance.WebResources/test/XrmGridRowControlMock.ts
> +    // TODO remove INamedComponent implementation which is bound by XrmCollectionMock
We would need to change the XrmCollectionMock to remove the implement reference.

2021-05-04 19:12 UTC, StephBrouil commented on src/Compliance.WebResources/src/services/AllegationService.ts
> +    }
I changed it to associateWithRelatedIssue

2021-06-17 18:24 UTC, pierluc-ssoucy approved these changes

2021-06-17 18:24 UTC, merged