Features/automatedchecklistresponses
opc-cpvp/OPC.PowerApps pull request #139
Opened 2021-03-17 01:49 UTC by mitchkirady

**Testing this PR can be done on "Compliance - PR - automatedchecklistresponses" environment**

PBI 857:
- Create "Recalculate Checklist Responses" field (two option) on Complaint (background field not added to form).
- Create plugin on Complaint Industry relationship (N:N), to set "Recalculate Checklist Response" flag to "Yes" on Complaint.
- Create flow on Checklist Response creation, to set "Recalculate Checklist Response" flag to "Yes" on Complaint.
- Create workflow on Complaint update (Complaint and Respondent Relationship), to set "Recalculate Checklist Response" flag to "Yes".
- Create flow to recalculate checklist responses based on industries and complainant/respondent relationship.

2021-03-29 21:23 UTC, GabrielFG requested changes
Here are my comments for now. Looks good, just some minor things which may need to be addressed. I've yet to make sure the CheclistControl.ts changes are fine as there may be something that isn't allowing the responses to fill out or I'm just not sure how the responses are not displaying. We can check this out together if you want.

2021-03-30 20:17 UTC, mitchkirady commented on src/Compliance.Solution/Data/Lookups/data.xml
>          <field name="ownerid" value="a7b80551-3c5d-eb11-89f5-000d3ae8e48a" lookupentity="systemuser" lookupentityname="Mitch Kirady" />
Thanks, it should definitely be Package Deployer, so I've made the change to a couple places.

2021-03-30 20:25 UTC, mitchkirady commented on src/Compliance.Solution/Solution/Workflows/Complaint-Update-SetChecklistResponse-2CE6974F-BF7B-EB11-A812-000D3AF47402.json
> +                    "industry": "9139"
Thanks for the heads up. The values are correct, but it looks like the official list of NAICS codes was modified on 2021-03-18. Perhaps these were added, since they don't show in my initial import file. I'll create a bug to add the missing codes, since there are likely others. Since this doesn't impact the flow's ability to run, I'll resolve this issue.

2021-03-30 22:18 UTC, mitchkirady commented
Applied changes to branch

2021-03-30 22:19 UTC, mitchkirady reviewed
Applied changes

2021-03-31 20:33 UTC, pierluc-ssoucy requested changes

2021-03-31 20:33 UTC, pierluc-ssoucy commented on src/Compliance.Plugins/RecalculateChecklistResponsesFlagPlugin.cs
> +                if ((localContext.PluginExecutionContext.MessageName != PluginMessage.Associate) ||
I wonder if we should track the dissociates as well in case one was added in error and removed, or if after review it's been changed.

2021-03-31 20:50 UTC, GabrielFG commented on src/Compliance.Plugins/RecalculateChecklistResponsesFlagPlugin.cs
> +                if ((localContext.PluginExecutionContext.MessageName != PluginMessage.Associate) ||
You're right, we would want to recalculate the checklist if a dissociation happens.

2021-03-31 21:09 UTC, GabrielFG commented on src/Compliance.Plugins/RecalculateChecklistResponsesFlagPlugin.cs
> +                if ((localContext.PluginExecutionContext.MessageName != PluginMessage.Associate) ||
I've made the change (not pushed yet) and seems to activate the flow, but unless I'm missing something, the flow will not change the checklist responses to their original values. This seems to be the case as the flow doesn't find the required associated industries that would set the checklist responses in the first place, as of course, they got dissociated. The flow will probably need to be changed to accommodate a dissociation too.

2021-03-31 21:29 UTC, mitchkirady commented on src/Compliance.Plugins/RecalculateChecklistResponsesFlagPlugin.cs
> +                if ((localContext.PluginExecutionContext.MessageName != PluginMessage.Associate) ||
Not only if the industry was added in error, but since the checklist response is read-only (because it's managed internally), you're right that we should probably have the flow auto-respond a "No" value, otherwise that question will never get answered. Thoughts? Good catch, @pierluc-ssoucy

2021-04-01 17:51 UTC, pierluc-ssoucy commented on src/Compliance.Plugins/RecalculateChecklistResponsesFlagPlugin.cs
> +                if ((localContext.PluginExecutionContext.MessageName != PluginMessage.Associate) ||
@mitchkirady That's right, I believe we had quickly discussed about this but we did not initially land on a decision, but now that we have it as a readonly, we should also updated the flow to auto-respond "no" as well.

2021-04-07 01:56 UTC, mitchkirady commented on src/Compliance.Solution/Solution/Workflows/Complaint-Update-SetRecalculateChecklistResponsesf-78FF9B2C-6D6E-4614-AEF3-AB84B6F0252B.xaml
> +<Activity x:Class="XrmWorkflow78ff9b2c6d6e4614aef3ab84b6f0252b" xmlns="http://schemas.microsoft.com/netfx/2009/xaml/activities" xmlns:mva="clr-namespace:Microsoft.VisualBasic.Activities;assembly=Syst
This workflow runs on update of the Complainant/Respondent relationship, so I'm not sure how it could be merged with the create flow. By keeping this, we are able to recalculate the checklist responses if the relationship is only determined at a later time. Thoughts?

2021-04-07 02:06 UTC, mitchkirady commented on src/Compliance.Solution/Solution/Workflows/ChecklistResponse-Create-SetRecalculateChecklistRe-D6FC1F33-AF86-EB11-A812-000D3A09D422.json
> +              "subscriptionRequest/filterexpression": "(_opc_questiontemplateid_value eq 6252b49c-ff6b-eb11-a812-000d3aff470c or _opc_questiontemplateid_value eq 1063d535-006c-eb11-a812-000d3aff470c
Comment added to flow

2021-04-08 01:57 UTC, mitchkirady commented on src/Compliance.Solution/Solution/Workflows/Complaint-Update-SetChecklistResponse-2CE6974F-BF7B-EB11-A812-000D3AF47402.json
> +        },
Commenting in flows has limited space, but I've added the industry names (sometimes shortened) in the comments of the flow steps which initialize the variables.

2021-04-08 03:01 UTC, mitchkirady commented on src/Compliance.Plugins/RecalculateChecklistResponsesFlagPlugin.cs
> +                if ((localContext.PluginExecutionContext.MessageName != PluginMessage.Associate) ||
The "No" response has been added to the flow when the recalculation happens.

2021-04-08 12:23 UTC, pierluc-ssoucy approved these changes
We may have an issue with the connection references, but i'll monitor the CD closely and fix it if its problematic.

2021-04-08 12:27 UTC, merged