Features/subprocess
opc-cpvp/OPC.PowerApps pull request #144
Opened 2021-04-12 20:43 UTC by pierluc-ssoucy

All hands on deck type of PR
- Task Templates
- Automatic generation of task per phase based on Task Templates
- Complaint Main Form modifications integrating the PCF
- Multilingual Plugin Tweaks to account for generated task
- Plugin Refactor

It also appears that Microsoft has done some significant changes to translations which are included in this already lengthy PR.

https://opc-compliance-tasks.crm3.dynamics.com/

2021-04-16 19:46 UTC, JonathanThomassin commented on src/Compliance.EarlyBound/Entities/opc_ChecklistType.cs
> +		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("opc_checklisttype_allegationtypes_checklistty")]
Do we want a different name because of the trimmed end?

2021-04-16 19:46 UTC, JonathanThomassin commented on src/Compliance.EarlyBound/OptionSets/opc_TaskType.cs
> +	}
It should be OOB numbering.

2021-04-16 19:46 UTC, JonathanThomassin commented on src/Compliance.EarlyBound/OptionSets/opc_tasktemplateStatusCode.cs
> +	}
It should be OOB numbering.

2021-04-16 19:46 UTC, JonathanThomassin commented on src/Compliance.Plugins.Tests/MultiLanguagePluginTests.cs
> +            public void translated_fields_should_contain_data()
Shouldn't those two be the same text?

2021-04-16 19:47 UTC, JonathanThomassin commented on src/Compliance.EarlyBound/Entities/opc_ChecklistType.cs
> +		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("opc_checklisttype_allegationtypes_checklistty")]
Should this relation name be different because of the trimmed end?

2021-04-16 19:47 UTC, JonathanThomassin commented on src/Compliance.EarlyBound/OptionSets/opc_TaskType.cs
> +		Situational = 3,
I think this should be OOB numbering.

2021-04-16 19:47 UTC, JonathanThomassin commented on src/Compliance.EarlyBound/OptionSets/opc_tasktemplateStatusCode.cs
> +		Inactive = 2,
I think this should be OOB numbering.

2021-04-16 19:49 UTC, JonathanThomassin commented on src/Compliance.Plugins.Tests/MultiLanguagePluginTests.cs
> +            public void fields_should_be_english_when_the_ui_is_english()
The naming is not the same.

2021-04-16 20:17 UTC, JonathanThomassin commented on src/Compliance.Plugins.Tests/MultiLanguagePluginTests.cs
> +            public void fields_should_be_english_when_the_ui_is_english()
Shouldn't those be the same

2021-04-16 20:18 UTC, JonathanThomassin commented on src/Compliance.Plugins.Tests/MultiLanguagePluginTests.cs
> +                    theme.opc_name.Should().StartWith(Prefix);
Do we want brackets for this?

2021-04-19 13:07 UTC, JonathanThomassin commented on src/Compliance.Plugins.Tests/MultiLanguagePluginTests.cs
>              public void timeline_records_strings_should_turn_to_correct_language(TimelineRecordTransform timelineRecordTransform)
Should this be the same?

2021-04-19 13:16 UTC, JonathanThomassin commented on src/Compliance.Plugins.Tests/QueueMembershipPluginTests.cs
> +            [Fact(DisplayName = "team queues shouldn't be associated ot users who are member through another team")]
Typo

2021-04-19 13:18 UTC, JonathanThomassin commented on src/Compliance.Plugins.Tests/QueueMembershipPluginTests.cs
> +            [Fact(DisplayName = "queue should not be disassociated from users whp are member through another team")]
Typo

2021-04-19 14:31 UTC, JonathanThomassin commented on src/Compliance.Plugins/MultiLanguagePlugin.cs
> +                userLanguage = Language.English;
Missing brackets

2021-04-19 14:35 UTC, JonathanThomassin commented on src/Compliance.Plugins/MultiLanguagePlugin.cs
>                  return;
Missing brackets.

2021-04-19 14:36 UTC, JonathanThomassin commented on src/Compliance.Plugins/MultiLanguagePlugin.cs
> +                preImage = localContext.PluginExecutionContext.PreEntityImages[PreImageAlias];
Missing brackets.

2021-04-19 14:39 UTC, JonathanThomassin commented on src/Compliance.Plugins/MultiLanguagePlugin.cs
> +                attributes.AddRange(preImage.Attributes.Where(a => !attributes.ContainsKey(a.Key)));
Missing brackets.

2021-04-19 14:39 UTC, JonathanThomassin commented on src/Compliance.Plugins/MultiLanguagePlugin.cs
>                  return;
Missing brackets.

2021-04-19 14:42 UTC, JonathanThomassin commented on src/Compliance.Plugins/MultiLanguagePlugin.cs
> +            if (response == null) return;
Not sure if we said that we should absolutely put curly brackets for every ifs or if some of them should be on the same line.

2021-04-19 15:08 UTC, JonathanThomassin commented on src/Compliance.Solution/Solution/AppModules/opc_compliance/AppModule.xml
> +    <AppModuleComponent type="60" id="{1fac7e2e-0b1c-4b6c-ab92-8af0f92dbdbc}" />
I can't find this form in the solution. The other two new lines under this one are good though.

2021-04-19 17:40 UTC, JonathanThomassin commented on src/Compliance.Solution/Solution/SdkMessageProcessingSteps/{e960b879-1816-ea11-a811-000d3af46489}.xml
>        <Attributes></Attributes>
Not sure I understand why there are two PreImage.

2021-04-19 18:04 UTC, JonathanThomassin commented on src/Compliance.Solution/Solution/Other/Relationships/opc_ChecklistType.xml
> +  </EntityRelationship>
I'm not sure what this relationship is for.

2021-04-19 18:21 UTC, JonathanThomassin commented
- The seed data for task templates will be added later right? Is there supposed to be test data in your environment?
- The font used for the label of the task component doesn't fit the rest of the form. Too bold and grey.
- I don't see Task Templates in any sitemap. Should we add a link?
- I think the Task Template main form's guid is missing from the solution.
- When you say that "Microsoft has done some significant changes to translations", are you talking about some of the french descriptions being modified or is it about the bunch of french labels getting removed?

2021-04-20 13:13 UTC, pierluc-ssoucy commented on src/Compliance.Solution/Solution/Other/Relationships/opc_ChecklistType.xml
> +  </EntityRelationship>
@JonathanThomassin I believe this is the relationship that allows to have multiple checklist associated to multiple allegation types and vice-versa.

2021-04-20 13:14 UTC, pierluc-ssoucy commented on src/Compliance.Solution/Solution/SdkMessageProcessingSteps/{e960b879-1816-ea11-a811-000d3af46489}.xml
>        <Attributes></Attributes>
@joshcampbell191

2021-04-20 13:15 UTC, pierluc-ssoucy commented on src/Compliance.EarlyBound/OptionSets/opc_TaskType.cs
> +	}
Looked slicker for badge configuration, but not mandatory. Are you aware of any issue this may cause?

2021-04-20 13:25 UTC, JonathanThomassin commented on src/Compliance.Solution/Solution/Other/Relationships/opc_ChecklistType.xml
> +  </EntityRelationship>
@pierluc-ssoucy Isn't the relationship:

Allegation Type -> Legislation/AllegationType -> Checklist Type ?

2021-04-20 13:49 UTC, JonathanThomassin commented on src/Compliance.EarlyBound/OptionSets/opc_TaskType.cs
> +	}
What's badge configuration?
And no I don't think this will cause any issue since we already do this on prem. I only mentioned this because of the guideline document.

2021-04-20 14:28 UTC, pierluc-ssoucy commented on src/Compliance.EarlyBound/OptionSets/opc_TaskType.cs
> +	}
@JonathanThomassin I thought I recalled something about that in the guideline when I read your comment. Badge configuration is for the new PCF. @mitchkirady can you foresee any issues with using those numbers? 

If not, should we bring it up to the team?

2021-04-20 14:41 UTC, JonathanThomassin commented on src/Compliance.EarlyBound/OptionSets/opc_TaskType.cs
> +	}
This right?
![image](https://user-images.githubusercontent.com/21164740/115415171-ae029980-a1c4-11eb-9582-b972e1e64ffc.png)

2021-04-20 14:59 UTC, pierluc-ssoucy commented on src/Compliance.Plugins/MultiLanguagePlugin.cs
> +            if (response == null) return;
Did it for now on behalf of @joshcampbell191, but we should setup a linter for C# as well.

2021-04-20 17:40 UTC, pierluc-ssoucy commented on src/Compliance.Solution/Solution/Other/Relationships/opc_ChecklistType.xml
> +  </EntityRelationship>
@JonathanThomassin I think you are right. @mitchkirady can you confirm if this is simply a remnant of development or a mismerged conflict?

2021-04-20 17:57 UTC, pierluc-ssoucy commented
> * The seed data for task templates will be added later right? Is there supposed to be test data in your environment? **Yes, and yes there was test data but i deleted it for some reason.**
> * The font used for the label of the task component doesn't fit the rest of the form. Too bold and grey. **Good point, wrong PR for this, but also not sure if I should match Timeline or default Panel titles, so I matched none**
> * I don't see Task Templates in any sitemap. Should we add a link? **Thoughts @mitchkirady**
> * I think the Task Template main form's guid is missing from the solution. **Thoughts @mitchkirady**
> * When you say that "Microsoft has done some significant changes to translations", are you talking about some of the french descriptions being modified or is it about the bunch of french labels getting removed? **Both I believe.**

2021-04-21 14:00 UTC, mitchkirady commented on src/Compliance.EarlyBound/OptionSets/opc_TaskType.cs
> +	}
@pierluc-ssoucy - There won't be any issues, but by default we usually stick to what's assigned OOB, since it's based on our Publisher.

2021-04-22 14:18 UTC, pierluc-ssoucy commented on src/Compliance.EarlyBound/OptionSets/opc_tasktemplateStatusCode.cs
> +	}
@JonathanThomassin this one is actually OOB.

2021-04-23 18:09 UTC, JonathanThomassin commented on src/Compliance.EarlyBound/OptionSets/opc_tasktemplateStatusCode.cs
> +	}
lol my bad... xD

2021-04-23 18:33 UTC, JonathanThomassin commented on src/Compliance.Solution/Solution/AppModules/opc_compliance/AppModule.xml
> +    <AppModuleComponent type="26" id="{6c272503-ab4e-eb11-a812-000d3a84ab5f}" />
There seems to be more than since last time.

Referenced in AppModule.xml only
b62ce022-cc0f-4c8c-bb29-21948f70dc74
1fac7e2e-0b1c-4b6c-ab92-8af0f92dbdbc
81a89014-442c-44ad-9725-4077426a7fee

Referenced in AppModule.xml and Solution.xml only
16654191-19ad-48ca-9e46-c4b4fbdad76f
d5b4a1b2-de4f-4f86-8768-b0730001e7d1

Good ones (They point to forms)
a1c8a6dc-8804-4019-9c78-7dbe86560ea1
6c272503-ab4e-eb11-a812-000d3a84ab5f

2021-04-23 19:17 UTC, JonathanThomassin commented on src/Compliance.Solution/Solution/SdkMessageProcessingSteps/{e960b879-1816-ea11-a811-000d3af46489}.xml
> +    </SdkMessageProcessingStepImage>
It came back! 😮

2021-04-23 19:22 UTC, JonathanThomassin commented on src/Compliance.Solution/Solution/Workflows/Complaint-Daily-CreateSLANotificationforERManagers-C19140C4-4429-EB11-A813-000D3A0C26F9.json
> +        "connection": {},
In the workflows, all the "connectionReferenceLogicalName" in the connection section of the of the connection references have been removed. Is that alright? (I put this here but I think it's in all workflows)

2021-04-23 19:23 UTC, JonathanThomassin commented on src/Compliance.Solution/Solution/Workflows/Complaint-Daily-CreateSLANotificationforERManagers-C19140C4-4429-EB11-A813-000D3A0C26F9.json
> +        "connection": {},
I think it is alright since the connections are different in each environments but I wanted to confirm.

2021-04-26 13:23 UTC, JonathanThomassin commented
When going out of a process stage and then going back in, do we want to reuse the existing tasks or we want to always create new ones?

2021-04-26 14:34 UTC, JonathanThomassin reviewed
@mitchkirady I made some tests and it looks like it recreates the completed and the skipped ones. I think I found two separate issues.

1- In step "Get open Tasks already linked to Complaint, excluding Analytical and Personal", it doesn't exclude analytical and personal since the numbers in the opc_type choice changed.
2- The flow that creates tasks doesn't look for existing task before creating new ones. This is only an issue when a case goes back in a stage that it was before.

2021-04-27 12:21 UTC, pierluc-ssoucy commented on src/Compliance.Solution/Solution/Workflows/Complaint-Daily-CreateSLANotificationforERManagers-C19140C4-4429-EB11-A813-000D3A0C26F9.json
> +        "connection": {},
Yes that's alright, I did this on purpose, although now that we have Gab's fix I can probably replace with the corret connection reference names

2021-05-10 22:47 UTC, joshcampbell191 commented on src/Compliance.Solution/Solution/Workflows/IndividualComplaint-CreateUpdate-GenerateTasks-8D2C036F-1356-EB11-A812-000D3AFF08CF.json
> +                  "fetchXml": "<fetch>\n   <entity name='task'>\n     <attribute name='activityid' />\n     <attribute name='statecode' />\n     <filter type='and'>\n       <condition attribute=\"sta
Should we store the task template ID in the task entity? That way we can avoid comparing all the fields (name, description and type) when checking to see if it exists. This would also work in cases where the name / description might change (although this is unlikely).

2021-05-11 13:53 UTC, pierluc-ssoucy commented on src/Compliance.Solution/Solution/Workflows/IndividualComplaint-CreateUpdate-GenerateTasks-8D2C036F-1356-EB11-A812-000D3AFF08CF.json
> +                  "fetchXml": "<fetch>\n   <entity name='task'>\n     <attribute name='activityid' />\n     <attribute name='statecode' />\n     <filter type='and'>\n       <condition attribute=\"sta
I feel like I brought this up before @mitchkirady, do you recall why we did not go with this?

2021-05-11 13:57 UTC, mitchkirady commented on src/Compliance.Solution/Solution/Workflows/IndividualComplaint-CreateUpdate-GenerateTasks-8D2C036F-1356-EB11-A812-000D3AFF08CF.json
> +                  "fetchXml": "<fetch>\n   <entity name='task'>\n     <attribute name='activityid' />\n     <attribute name='statecode' />\n     <filter type='and'>\n       <condition attribute=\"sta
That's a good point, and I considered this option too when doing the compare, but forgot to bring it up. I don't see any issues with adding this capability and modifying the compare step. I agree that it would work better that way. @pierluc-ssoucy @joshcampbell191 - Let me know if you'd like me to make the change.

2021-05-11 14:24 UTC, pierluc-ssoucy commented on src/Compliance.Solution/Solution/Workflows/Complaint-Daily-CreateSLANotificationforERManagers-C19140C4-4429-EB11-A813-000D3A0C26F9.json
> +        "connection": {},
@joshcampbell191 there's plenty like this right now, let's fix them as part of @GabrielFG's PR.

2021-05-11 14:25 UTC, pierluc-ssoucy commented on src/Compliance.Solution/Solution/Workflows/IndividualComplaint-CreateUpdate-GenerateTasks-8D2C036F-1356-EB11-A812-000D3AFF08CF.json
> +                  "fetchXml": "<fetch>\n   <entity name='task'>\n     <attribute name='activityid' />\n     <attribute name='statecode' />\n     <filter type='and'>\n       <condition attribute=\"sta
@mitchkirady I think this one does make sense, let's go with it.

2021-05-11 14:25 UTC, mitchkirady commented on src/Compliance.Solution/Solution/Entities/opc_tasktemplate/SavedQueries/{e4b53e3b-893f-428a-a43e-cd48cb99b8e4}.xml
> +          <cell name="opc_sequence" width="100" />
yes, i agree.

2021-05-20 14:53 UTC, JonathanThomassin requested changes
I think it's the last thing to fix.
This is for the Generate Tasks flow.
In "Check if generated task matches an existing skipped task", it should not ignore the open tasks since Analytics tasks don't get canceled when you change stage. This means that they get recreated when going back to a previous stage. I would also rename "Check if generated task matches an existing skipped task" because it is a Get List action. "Get list of existing tasks that match the task template" might be better.

2021-05-25 20:23 UTC, JonathanThomassin requested changes
I tested the flow and it looks good.
There are a couple of issues but we're close.

2021-05-26 12:32 UTC, pierluc-ssoucy commented on src/Compliance.WebResources/.husky/pre-commit
> +#!/bin/sh
I believe it should be there @joshcampbell191 ?

2021-05-26 12:34 UTC, joshcampbell191 commented on src/Compliance.WebResources/.husky/pre-commit
> +#!/bin/sh
The folder is required as it replaces the .huskyrc configuration file.

2021-05-26 18:27 UTC, JonathanThomassin approved these changes

2021-05-26 18:30 UTC, merged