Features/ownerteams
opc-cpvp/OPC.PowerApps pull request #195
Opened 2021-04-28 23:52 UTC by mitchkirady

- Remove dependency on Queues
- Use Owner Teams for complaint ownership
- Replicate queue item views on complaints entity
- Add Priority Score on complaint
- Update flows and processes for priority score, and complaint routing
- Delete custom components from queue items
- Update charts, views, and dashboards to replace queue item components by complaints

2021-05-12 20:58 UTC, pierluc-ssoucy requested changes

2021-05-12 20:58 UTC, pierluc-ssoucy commented on src/Compliance.Solution/Solution/Workflows/IndividualComplaint-CreateUpdate-RoutingRule-0B8AC528-6E5D-EA11-A811-000D3AF464F8.json
> +                      "operationId": "UpdateRecord",
Should we be using the "Relate" action instead of the update? For this one and the others.

2021-05-14 20:47 UTC, mitchkirady commented on src/Compliance.Solution/Solution/Entities/opc_complaint/SavedQueries/{4ff54d49-10a3-eb11-b1ac-000d3a09ddee}.xml
> +      <LocalizedName description="Active Complaints in Selected Teams" languagecode="1033" />
Actually it doesn't so I've removed the view.

2021-05-17 18:05 UTC, mitchkirady commented on src/Compliance.Solution/Solution/Entities/opc_complaint/Visualizations/{30BD9124-D5A5-EB11-9442-000D3AF48827}.xml
> +            <attribute name="opc_complaintid" aggregate="count" alias="_CRMAutoGen_aggregate_column_Num_0" />
This is created for the charts, this one is "Complaints by Resource".

2021-05-17 18:06 UTC, mitchkirady commented on src/Compliance.Solution/Solution/Entities/opc_complaint/Visualizations/{B12456D3-D4A5-EB11-9442-000D3AF48827}.xml
> +            <attribute name="opc_complaintid" aggregate="count" alias="_CRMAutoGen_aggregate_column_Num_0" />
This is created for the charts, so we need it. This one is "Complaints by Last Milestone".

2021-05-17 18:29 UTC, mitchkirady commented on src/Compliance.Solution/Solution/Workflows/IndividualComplaint-CreateUpdate-RoutingRule-0B8AC528-6E5D-EA11-A811-000D3AF464F8.json
> +                      "operationId": "UpdateRecord",
The "Relate" action is great for associating to 1:M or M:M, but for lookups, it needs to be an update.

2021-05-25 18:33 UTC, pierluc-ssoucy approved these changes

2021-05-25 18:33 UTC, merged