Bugs/flow status
opc-cpvp/OPC.PowerApps pull request #203
Opened 2021-04-29 19:10 UTC by GabrielFG

- New PowerShell script to be used in the release pipeline to:
  - Tie the connections and connection references either by configuration or by name
  - Turn on the flows if the connections and connection references are tied properly
  - The script mitigates having to always turn flows back on after cleaning/releasing an environment and also prevents the creation of new connection references as the same ones are always used

- Changed the names of the connection references in the solution to have some kind of matching value between them and the connections
- Changed build pipeline to copy all scripts to the artifact that are under the azure-pipelines script folder

2021-05-14 12:13 UTC, pierluc-ssoucy requested changes

2021-05-14 12:13 UTC, pierluc-ssoucy commented on azure-pipelines/scripts/update_connection_references.ps1
> +            $impersonationConn.OrganizationWebProxyClient.CallerId = $impersonationCallerId
I believe we had talked about it, but did we consider forcing the user to always be our app registration (perhaps passing the identity as a param)?

2021-05-14 12:13 UTC, pierluc-ssoucy commented on azure-pipelines/scripts/update_connection_references.ps1
> +                }
The way this is written, it looks like its looking for a single match. If that is truly what it is, to make it clearer we should exit the foreach.

2021-05-25 14:38 UTC, GabrielFG commented on azure-pipelines/scripts/update_connection_references.ps1
> +            $impersonationConn.OrganizationWebProxyClient.CallerId = $impersonationCallerId
From the looks of the Admin Power Apps commands, you can give "CanEdit" permissions to users to the connection and then maybe we'll be able to change the connection reference user too. It can maybe manage to work like that but it's possible we'll still need to impersonate. Also not sure what the "CanEdit" permission will entail (would all flows run properly with that account?) and if it will give the same rights as the original user that created the connection in the first place. I can test this out if you want.

2021-05-25 18:54 UTC, pierluc-ssoucy commented on azure-pipelines/scripts/update_connection_references.ps1
> +            $impersonationConn.OrganizationWebProxyClient.CallerId = $impersonationCallerId
That would be interesting to explore, but I don't think this a show stopper for now, current code already gets us beyond 80% there.

2021-06-15 12:26 UTC, pierluc-ssoucy approved these changes

2021-06-15 12:26 UTC, merged