Features/ownerteams roles
opc-cpvp/OPC.PowerApps pull request #284
Opened 2021-05-31 15:23 UTC by JonathanThomassin

- Replaced N:N relationship between Queues and Teams with a N:N relationship between Teams and Teams.
- Added code in Compliance Deployment to add roles and AAD teams to the Owner teams. 
Also added more AAD Teams to the list.
- Removed AAD Teams from seed data.
- Created new roles matching the new AAD teams and added them to the solution.
- Renamed and modified the QueueMembership plugin for Owner Teams Membership and added tests for it.
- Renamed and modified the Queue Membership flow fir Team Membership.

2021-06-03 13:12 UTC, pierluc-ssoucy requested changes

2021-06-03 13:12 UTC, pierluc-ssoucy commented on src/Compliance.Solution/Solution/Workflows/TeamMembership-Daily-RefreshOwnerTeamMembershipfro-928D6736-9CB4-EA11-A812-000D3AF46FFF.json
> +{
I am not sure if this was like this before, or if its an issue or not, but I went through logs of 2 runs and it looks like it should trigger the plugin 22 times (associate and dissociate), but it looks like there is 46 tracelogs per flow run, which does not really lineup.

2021-06-03 13:12 UTC, pierluc-ssoucy commented on src/Compliance.Plugins/OwnerTeamMemberShipPlugin.cs
> +            }
This is the old school version of .Any() :)

2021-06-03 14:00 UTC, JonathanThomassin commented on src/Compliance.Solution/Solution/Other/Relationships.xml
> +  <EntityRelationship Name="opc_teams_teams_membership" />
I thought about it but wasn't sure if it was breaking our naming conventions. It would probably make sense to have an exception for self referencing relationship.

2021-06-03 14:28 UTC, JonathanThomassin commented on src/Compliance.Plugins/OwnerTeamMemberShipPlugin.cs
> +            ownerTeamId = new[] { target.Id };
Yes. Even when you open the related tab of an AAD team, go to the owner grid and add an owner.

2021-06-03 14:39 UTC, JonathanThomassin commented on src/Compliance.WebResources/src/forms/TeamMainForm.test.ts
> +    describe("when form is initializing", () => {
I'm not sure what test I should be doing though.

2021-06-03 15:43 UTC, JonathanThomassin commented on src/Compliance.Solution/Solution/Workflows/TeamMembership-Daily-RefreshOwnerTeamMembershipfro-928D6736-9CB4-EA11-A812-000D3AF46FFF.json
> +{
After testing it multiple times I think it is a normal behavior. If you dont mind I can show you what I got this afternoon.

2021-06-03 16:22 UTC, pierluc-ssoucy commented on src/Compliance.WebResources/src/forms/TeamMainForm.test.ts
> +    describe("when form is initializing", () => {
Probably something like making sure setVisible is not called when on create.

2021-06-03 16:34 UTC, pierluc-ssoucy commented on src/Compliance.Solution/Solution/Other/Relationships.xml
> +  <EntityRelationship Name="opc_teams_teams_membership" />
probably not the end of the world either way, as there probably won't ever be another teams to teams relationship, I'll leave it up to you.

2021-06-04 12:31 UTC, JonathanThomassin commented on src/Compliance.Solution/Solution/Other/Relationships.xml
> +  <EntityRelationship Name="opc_teams_teams_membership" />
changed it to opc_teams_teams_owneraadassociation

2021-06-04 20:20 UTC, pierluc-ssoucy approved these changes

2021-06-07 11:57 UTC, merged